on:
  workflow_call:
    inputs:
      image:
        type: string
        required: true
        description: container image to deploy
      tag:
        type: string
        required: true
        description: container image tag to deploy
      namespace:
        type: string
        required: false
        default: default
        description: deployment namespace
      deployment-name:
        type: string
        required: true
        description: deployment name
      container-name:
        type: string
        required: true
        description: container name
    secrets:
      kubernetes-server:
        required: true
        description: kubernetes api server url
      kubernetes-token:
        required: true
        description: kubernetes api server authentication token
      kubernetes-cert:
        required: true
        description: kubernetes api server certificate

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Kubernetes cluster
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        run: |
          kubectl config set-credentials default --token=${{ secrets.kubernetes-token }}
          echo ${{ secrets.kubernetes-cert }} | base64 -d > ca.crt
          kubectl config set-cluster default --server=${{ secrets.kubernetes-server }} --certificate-authority=ca.crt
          kubectl config set-context default --cluster=default --user=default
          kubectl config use-context default
          kubectl set image deployment/${{ inputs.deployment-name }} ${{ inputs.container-name }}=${{ inputs.image }}:${{ inputs.tag }} -n ${{ inputs.namespace }}
