name: pipeline

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v6
      - name: Check workflow files
        uses: reviewdog/action-actionlint@v1
        with:
          fail_level: error
