name: pipeline

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v7
      - name: Check workflow files
        uses: raven-actions/actionlint@v2
