on:
  workflow_call:
    inputs:
      rust-version:
        type: string
        required: false
        default: stable
        description: rust version to use to update dependencies
      author:
        type: string
        required: false
        default: 'Bot <noreply@ectobit.com>'
        description: pull request author
      committer:
        type: string
        required: false
        default: 'Bot <noreply@ectobit.com>'
        description: commit author
      reviewers:
        type: string
        required: false
        default: acim
        description: persons to review the pull request
    secrets:
      token:
        required: false
        description: personal access token to make pull request

jobs:
  update-deps:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ inputs.rust-version }}
      - name: Check out
        uses: actions/checkout@v5
      - name: Update dependencies
        run: |
          cargo update --aggressive
      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        env:
          token: ${{ secrets.token }}
        if: ${{ env.token == '' }}
        with:
          title: 'update dependencies'
          branch: update-deps
          commit-message: 'update dependencies'
          author: ${{ inputs.author }}
          committer: ${{ inputs.committer }}
          delete-branch: true
          reviewers: ${{ inputs.reviewers }}
      - name: Create pull request using token
        uses: peter-evans/create-pull-request@v7
        env:
          token: ${{ secrets.token }}
        if: ${{ env.token != '' }}
        with:
          token: ${{ secrets.token }}
          title: 'update dependencies'
          branch: update-deps
          commit-message: 'update dependencies'
          author: ${{ inputs.author }}
          committer: ${{ inputs.committer }}
          delete-branch: true
